### ISSUE TITLE
RTL text is not aligned correctly

### ISSUE THREAD

**Issue by Ahmedd-0** [Ristellise/AegisubDC#4]
RTL language text align and text selecting is not working correctly. In first pic the selected part is not the highlighted one but the empty space between the two letter groups. And if I insert a LTR letter there, the original text gets inverted around it.
This issue happens in both the official release and this fork.

_About selecting, it selects the char in the same position from the other side like if i select the char that is 5cm from the left end it will select the char that is 5cm from the right._

![image](https://user-images.githubusercontent.com/58073464/102237506-cce6db80-3f05-11eb-892e-1a119f552652.png)
![image](https://user-images.githubusercontent.com/58073464/102237515-cfe1cc00-3f05-11eb-8edd-aa9d48d9ec9d.png)

**Comment by SSgumS** [comment]
The problem was always a bother. When you want to edit the line and for example add a word in the middle of the line, because of the ltr nature of the edit box, you can't find the appropriate location easily. I use Ctrl to navigate between words to have clue about the location. Another workaround that we rtl funsubbers use is using a dialog box to edit the text. See RTL Editor feature in these repos: [MasafAutomation](https://github.com/Majid110/MasafAutomation), [Aegisub Persian Toolkit](https://github.com/mzn928/Aegisub_Persian-Toolkit)
It would be so great if the edit box of Aegisub could handle rtl languages as well as in it's dialogs. It seems that the solution would be easy. Hope to see the fix soon.

**Comment by Ristellise** [comment]
Seems like a underlying dependency issue:  
> Scintilla provides only limited experimental support on Windows for right-to-left languages like Arabic and Hebrew. While text in these languages may appear correct, interaction with this text may not work correctly as occurs with other editors.  

Source: https://www.scintilla.org/ScintillaDoc.html

Unless someone could convince the people at Scintilla to fix it, I can't do anything on my end.

**Comment by Ristellise** [comment]
Implemented with Release 9213. Use non-STC
